name: flare_example
version: 0.2.0
author: George Moschovitis <george.moschovitis@gmail.com>
description: An example site rendered by Flare, a Dart-powered static-site generator.
dev_dependencies:
  flare: any
  sass: any
transformers:
- sass:
    executable: /home/gmosx/Code/sassc
- flare/metadata_extractor
- flare/metadata_transformer
- flare/markdown_transformer
- flare/posts_indexer:
    root: web/posts
- flare/posts_transformer:
    root: web/posts
    layout: web/_posts_layout.tmpl.html
- flare/partials_transformer
- flare/metadata_aggregator
- flare/mustache_transformer
- flare/html_optimizer
- flare/cleanup_transformer
